baseURL = 'https://przemyslawbarski.netlify.app/'
defaultContentLanguage = 'pl'
disableKinds = ['taxonomy', 'term']

[languages]
  [languages.pl]
    weight = 2
  [languages.en]
    weight = 1

[params]
  title_prefix = 'Przemysław Barski - '
